### ISSUE TITLE
Renaming directory from mbqc to ubqc

### ISSUE THREAD

**Issue by cgmcintyr** [cgmcintyr/SimulaQron#3]
Should we rename `examples/mbqc` to  `examples/ubqc` as we managed to implement UBQC?

**Comment by cgmcintyr** [comment]
@shraggy @mayaobobby @marcibra @blindclouder1

**Comment by shraggy** [comment]
Oh yes, this one should be named UBQC! We could have another folder with
measurement.py and flow.py along with the subroutine for MBQC (to be coded)
to implement only MBQC.

**Comment by BlindQlouder** [comment]
sounds good. I could finish the MBQC I was working on on Sunday. Also, 
we could just implement the clean circuit on simulaqron directly, so 
that we can compare the result of MBQC or UBQC to it. Just to make sure 
it really works. Yao volunteers to implement this clean circuit.

**Comment by shraggy** [comment]
Alright. That works. After we are done testing circuits and eliminating any
existing bug, maybe I'll try to incorporate *resource states* later with
the *quantum Input/output* version (two proposed extensions of the
project). That would be make it complete a complete UBQC project! :)

**Comment by shraggy** [comment]
Hey everyone!

In order to make it a fully automated UBQC protocol we just need final 4 steps: Current protocol is fit for only Clifford operations. In order to make it Universal we need to add translation for phase gates

Zeroth phase: For Universal Quantum computation (all possible gates in QC)
1)Add a translation for Phase gates in measurement subroutine

First Phase: Quantum Input/ Output (Current protocol is fit for only classical input/output)
1) New: Input qubits taken as input from the Client before running MBQC
2) New: Quantum One Time Pad these input states in UBQC Client protocol
3) Replace: Create number of (total qubits-input qubits) random qubits and send these with input qubits to the Server
4) Send unmeasured output qubits back to the Client
5) Remove one time pad from Client's output qubits and store these in output qubit array for Client

Second Phase: Adding a resource state: example cluster states (a separate subroutine)
1) Accepts result from before Flow. Estimate dimension of resource state
2) Calculate measurement angles for unnecessary qubits
3) Update computation angle steps for necessary qubits affected by above unnecessary qubits
4) Send result to the Client protocol

Third Phase: Verififiable UBQC
1) Needs extra "trap qubits"
2) Needs extra test to verify using a threshold value and accept results or abort protocol by Client.

The last two phases are for later but we can make minor changes to include zeroth and first phases.

**Comment by shraggy** [comment]
fully automated UBQC protocol*

**Comment by BlindQlouder** [comment]
Hi all,

to me that looks like 11 steps:) But may be it is less difficult than it 
looks.

I already did 1.1 as my mbqc function takes quantum states in and 
returns the output quantum states. I pushed this and some other changes 
to develop, in case you didn't see.

We also just found the replacement rules for rotations thanks to Anne. 
Looks like this would require three more cases for the measurement 
routine, for the three general rotations around X Y and Z, correct?

**Comment by shraggy** [comment]
4 phases* .. my bad😅. The input qubits need to be taken as an input for Measurement.py (i.e. when we record gates and qubit addresses in the JSON file). The idea is Client supplies her input qubits and operation of gates before this program ( which includes measurement.py, flow.py, Client.py, Server.py ) and as an output she gets her output quantum qubits. Thus, the program would be a fully automated UBQC gadget.

**Comment by mayaobobby** [comment]
Hello all,

I just submit the latest version of UBQC with "Add a translation for Phase
gates in measurement subroutine". After verification, it seems working
correctly.

Regards
Yao

**Comment by cgmcintyr** [comment]
We might want to use pull requests for submitting code changes? That way we can do code reviews and understand what was added :)

**Comment by BlindQlouder** [comment]
Yes, sorry for messing this up. I will do that in the future.

**Comment by cgmcintyr** [comment]
No worries, just seeing that amount of work, well we all have write access and not a lot of tests. 

Pull requests should help us avoid coding ourselves into a bowl of spaghetti.
